#!/bin/sh
### BEGIN INIT INFO
# Provides:          pve-sdn-commit
# Required-Start:    $network pve-cluster
# Required-Stop:
# Should-Start:      frr corosync
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Commit Proxmox VE SDN changes
### END INIT INFO

# LSB counterpart of pve-sdn-commit.service.

. /lib/lsb/init-functions

HELPER=/usr/share/pve-manager/helpers/pve-sdn-commit

test -x $HELPER || exit 0

case "$1" in
    start)
        log_action_begin_msg "Committing Proxmox VE SDN changes"
        $HELPER
        status=$?
        log_action_end_msg $status
        exit $status
        ;;
    stop|restart|reload|force-reload)
        ;;
    status)
        exit 0
        ;;
    *)
        echo "Usage: /etc/init.d/pve-sdn-commit {start|stop|status}" >&2
        exit 3
        ;;
esac
