#!/bin/sh
### BEGIN INIT INFO
# Provides:          pvedaemon
# Required-Start:    $remote_fs $network $syslog pve-cluster
# Required-Stop:     $remote_fs $network $syslog pve-cluster
# Should-Start:      corosync
# Should-Stop:       corosync
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PVE API Daemon
### END INIT INFO

# LSB counterpart of pvedaemon.service. The daemon forks and manages its pid
# file itself, so this only wraps its start/stop/restart commands.

. /lib/lsb/init-functions

NAME=pvedaemon
DESC="PVE API Daemon"
DAEMON=/usr/bin/pvedaemon
PIDFILE=/run/pvedaemon.pid

test -x $DAEMON || exit 0

case "$1" in
    start)
        # see debian/tmpfiles, /run is a tmpfs
        install -d -m 0750 -o root -g www-data /run/pve
        log_daemon_msg "Starting $DESC" "$NAME"
        $DAEMON start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        $DAEMON stop
        log_end_msg $?
        ;;
    restart|reload|force-reload)
        # like ExecReload= in the unit, a graceful re-exec of the daemon
        log_daemon_msg "Restarting $DESC" "$NAME"
        $DAEMON restart
        log_end_msg $?
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}" >&2
        exit 3
        ;;
esac
