#!/bin/sh
### BEGIN INIT INFO
# Provides:          pvestatd
# Required-Start:    $remote_fs $network $syslog pve-cluster pvenetcommit
# Required-Stop:     $remote_fs $network $syslog pve-cluster
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PVE Status Daemon
### END INIT INFO

# LSB counterpart of pvestatd.service.

. /lib/lsb/init-functions

NAME=pvestatd
DESC="PVE Status Daemon"
DAEMON=/usr/bin/pvestatd
PIDFILE=/run/pvestatd.pid

# tell the daemon it's run by the init system, so that it acts directly
# instead of asking the init system, i.e. running this script again
export PVE_INIT_SCRIPT=1

test -x $DAEMON || exit 0

case "$1" in
    start)
        # see debian/tmpfiles, /run is a tmpfs; pvestatd writes metrics there
        install -d -m 0750 -o root -g www-data /run/pve
        log_daemon_msg "Starting $DESC" "$NAME"
        $DAEMON start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        $DAEMON stop
        log_end_msg $?
        ;;
    restart|reload|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        $DAEMON restart
        log_end_msg $?
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}" >&2
        exit 3
        ;;
esac
