#!/bin/sh
### BEGIN INIT INFO
# Provides:          spiceproxy
# Required-Start:    $remote_fs $network $syslog pveproxy
# Required-Stop:     $remote_fs $network $syslog pveproxy
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PVE SPICE Proxy Server
### END INIT INFO

# LSB counterpart of spiceproxy.service.

. /lib/lsb/init-functions

NAME=spiceproxy
DESC="PVE SPICE Proxy Server"
DAEMON=/usr/bin/spiceproxy
PIDFILE=/run/pveproxy/spiceproxy.pid

# tell the daemon it's run by the init system, so that it acts directly
# instead of asking the init system, i.e. running this script again
export PVE_INIT_SCRIPT=1

test -x $DAEMON || exit 0

case "$1" in
    start)
        # starting a running daemon succeeds, as with systemctl start (LSB);
        # the daemon's own start command fails then
        if pidofproc -p $PIDFILE $DAEMON >/dev/null; then
            log_action_msg "$DESC is already running"
            exit 0
        fi
        log_daemon_msg "Starting $DESC" "$NAME"
        $DAEMON start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        $DAEMON stop
        log_end_msg $?
        ;;
    restart|reload|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        $DAEMON restart
        log_end_msg $?
        ;;
    status)
        status_of_proc -p $PIDFILE $DAEMON $NAME
        ;;
    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload|force-reload|status}" >&2
        exit 3
        ;;
esac
